// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/1278651995/go-demos/scene/seckill/seckill03/ent/merchandise"
)

// MerchandiseCreate is the builder for creating a Merchandise entity.
type MerchandiseCreate struct {
	config
	mutation *MerchandiseMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (mc *MerchandiseCreate) SetUID(s string) *MerchandiseCreate {
	mc.mutation.SetUID(s)
	return mc
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableUID(s *string) *MerchandiseCreate {
	if s != nil {
		mc.SetUID(*s)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MerchandiseCreate) SetCreatedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableCreatedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MerchandiseCreate) SetUpdatedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableUpdatedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetUpdatedAt(*t)
	}
	return mc
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (mc *MerchandiseCreate) SetDeactivatedAt(t time.Time) *MerchandiseCreate {
	mc.mutation.SetDeactivatedAt(t)
	return mc
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableDeactivatedAt(t *time.Time) *MerchandiseCreate {
	if t != nil {
		mc.SetDeactivatedAt(*t)
	}
	return mc
}

// SetStock sets the "stock" field.
func (mc *MerchandiseCreate) SetStock(u uint) *MerchandiseCreate {
	mc.mutation.SetStock(u)
	return mc
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (mc *MerchandiseCreate) SetNillableStock(u *uint) *MerchandiseCreate {
	if u != nil {
		mc.SetStock(*u)
	}
	return mc
}

// Mutation returns the MerchandiseMutation object of the builder.
func (mc *MerchandiseCreate) Mutation() *MerchandiseMutation {
	return mc.mutation
}

// Save creates the Merchandise in the database.
func (mc *MerchandiseCreate) Save(ctx context.Context) (*Merchandise, error) {
	var (
		err  error
		node *Merchandise
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MerchandiseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			if node, err = mc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			if mc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MerchandiseCreate) SaveX(ctx context.Context) *Merchandise {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MerchandiseCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MerchandiseCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MerchandiseCreate) defaults() {
	if _, ok := mc.mutation.UID(); !ok {
		v := merchandise.DefaultUID()
		mc.mutation.SetUID(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := merchandise.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		v := merchandise.DefaultUpdatedAt()
		mc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mc.mutation.Stock(); !ok {
		v := merchandise.DefaultStock
		mc.mutation.SetStock(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MerchandiseCreate) check() error {
	if _, ok := mc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Merchandise.uid"`)}
	}
	if v, ok := mc.mutation.UID(); ok {
		if err := merchandise.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Merchandise.uid": %w`, err)}
		}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Merchandise.created_at"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Merchandise.updated_at"`)}
	}
	if _, ok := mc.mutation.Stock(); !ok {
		return &ValidationError{Name: "stock", err: errors.New(`ent: missing required field "Merchandise.stock"`)}
	}
	return nil
}

func (mc *MerchandiseCreate) sqlSave(ctx context.Context) (*Merchandise, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MerchandiseCreate) createSpec() (*Merchandise, *sqlgraph.CreateSpec) {
	var (
		_node = &Merchandise{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: merchandise.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: merchandise.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.UID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: merchandise.FieldUID,
		})
		_node.UID = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := mc.mutation.DeactivatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: merchandise.FieldDeactivatedAt,
		})
		_node.DeactivatedAt = &value
	}
	if value, ok := mc.mutation.Stock(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: merchandise.FieldStock,
		})
		_node.Stock = value
	}
	return _node, _spec
}

// MerchandiseCreateBulk is the builder for creating many Merchandise entities in bulk.
type MerchandiseCreateBulk struct {
	config
	builders []*MerchandiseCreate
}

// Save creates the Merchandise entities in the database.
func (mcb *MerchandiseCreateBulk) Save(ctx context.Context) ([]*Merchandise, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Merchandise, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MerchandiseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MerchandiseCreateBulk) SaveX(ctx context.Context) []*Merchandise {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MerchandiseCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MerchandiseCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
