// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/1278651995/go-demos/scene/seckill/seckill03/ent/merchandise"
	"github.com/1278651995/go-demos/scene/seckill/seckill03/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	merchandiseMixin := schema.Merchandise{}.Mixin()
	merchandiseMixinFields0 := merchandiseMixin[0].Fields()
	_ = merchandiseMixinFields0
	merchandiseFields := schema.Merchandise{}.Fields()
	_ = merchandiseFields
	// merchandiseDescUID is the schema descriptor for uid field.
	merchandiseDescUID := merchandiseMixinFields0[0].Descriptor()
	// merchandise.DefaultUID holds the default value on creation for the uid field.
	merchandise.DefaultUID = merchandiseDescUID.Default.(func() string)
	// merchandise.UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	merchandise.UIDValidator = func() func(string) error {
		validators := merchandiseDescUID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(uid string) error {
			for _, fn := range fns {
				if err := fn(uid); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// merchandiseDescCreatedAt is the schema descriptor for created_at field.
	merchandiseDescCreatedAt := merchandiseMixinFields0[1].Descriptor()
	// merchandise.DefaultCreatedAt holds the default value on creation for the created_at field.
	merchandise.DefaultCreatedAt = merchandiseDescCreatedAt.Default.(func() time.Time)
	// merchandiseDescUpdatedAt is the schema descriptor for updated_at field.
	merchandiseDescUpdatedAt := merchandiseMixinFields0[2].Descriptor()
	// merchandise.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	merchandise.DefaultUpdatedAt = merchandiseDescUpdatedAt.Default.(func() time.Time)
	// merchandise.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	merchandise.UpdateDefaultUpdatedAt = merchandiseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// merchandiseDescStock is the schema descriptor for stock field.
	merchandiseDescStock := merchandiseFields[0].Descriptor()
	// merchandise.DefaultStock holds the default value on creation for the stock field.
	merchandise.DefaultStock = merchandiseDescStock.Default.(uint)
}
